name: Build and Deploy APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Deploy Debug
        run: ./gradlew assembleRelease appDistributionUploadRelease
        env:
          FIREBASE_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.APP_ID }}
          token:
          file: app/build/outputs/apk/debug/ReCall-debug.apk
          groups: Testers
